[package]
name = "wasm-project"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = { version = "0.2.100", features = ["serde-serialize"] }
serde-wasm-bindgen = "0.6.5"

[lib]
crate-type = ["cdylib", "rlib"]
